apiVersion: v1
kind: Service
metadata:
  name: attendance-backend-service
spec:
  selector:
    app: attendance-backend
  ports:
    - protocol: TCP
      port: 50001
      targetPort: 50001
  type: LoadBalancer
