apiVersion: v1
kind: Service
metadata:
  name: attendance-frontend-service
spec:
  selector:
    app: attendance-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
